server:
  port: 8082

base-url:
  context: /api/library/v1.0

spring:
  cloud:
    gcp:
      sql:
        enabled: false
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/userdatabasecloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    maxIdle: "10"
    maxActive: "20"
    maxWait: "2000"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false



log:
  identifierKey: UUID

cloudlet:
  ip: 192.168.8.131
  port: 8083

python:
  pluginFilePath: "..\\server\\src\\main\\java\\com\\janitha\\videoenhancer\\client\\external\\cloudletPlugins"
  pythonPath : "C:\\Users\\janitha\\AppData\\Local\\Programs\\Python\\Python310\\python"
